### ISSUE TITLE
Rating song doesn't apply to specific version of song

### ISSUE THREAD

**Issue by cirdanlunae** [AF-1/lms-ratingslight#1] opened 2023-07-10 06:53 UTC
## DESCRIBE THE BUG

When rating a song, it sometimes won't appear to rate the song in LMS Material Skin. However, another version of the song has been rated. Example:

"Everlong" by Foo Fighters on The Colour and the Shape is rated 5 stars. No rating appears. However, on the album Greatest Hits, "Everlong" is rated 5 stars. 

<br><br>
## TO REPRODUCE
1. Have a song that appears on two separate albums by same artist with same track title
2. Rate the song on one of the albums. If it successfully rates, try re-setting rating on the other version.
3. One of the two will not rate, and will rate for the other.

<br><br>
## EXPECTED BEHAVIOR
The rating should apply to the album version of the track being rated.

<br><br>
## VERSION INFO
* LMS version: v8.3.1
* OS (version): piCorePlayer v8.2.0
* Plugin version: v2.3.9
* Web skin/controller: Material, also Default
* Browser (version): Firefox 114.0.2, also Melodeon

<br><br>
## SCREENSHOTS
Here is a recording of the bug in action:
https://youtu.be/zUqorbAH97E

**Comment by AF-1** [comment] 2023-07-10 16:11
What you're seeing appears to be a (caching) problem with title formats (e.g. "TITLE RL_RATING_STARS_APPENDED"). They seem to be cached by LMS (even if you tell it not to). I've seen a similar problem with another plugin. 

It does not seem to affect the tracks in the client playlist queue. So if you add both tracks to the client's playlist queue and change their rating values you should see the correct values after a short while. And the title formats got updated (sometimes?) in Material, may be because it uses its own way to refresh the browse view.

FWICS all rating values are correctly written to the LMS database and displayed correctly on the song details page, in the context menus or in the client playlist queue. It's just the title formats that don't get refreshed by LMS.

BTW unless you use symbolic links and such you don't need to worry about tracks with identical track names getting rated. Whenever you rate a track in Material or with any other UI/controller, they send the _unique_ track id/url for this specific track. Since it's unique, only this track gets rated. As mentioned, to verify a track's changed rating value check the song details page, its context menu or the client playlist queue if it's in there.

I haven't changed anything related to title formats in a long time. After a quick look at LMS I don't think a change happened there either in the last couple of months.
At the moment, I don't think I can solve this in the plugin. As soon as @michaelherger is back from holiday, I'll ask him.

**Comment by AF-1** [comment] 2023-07-20 09:57
I can no longer replicate your issue using these versions: 

> LMS 8.4.0 - 1688469516 @ Tue Jul 4
> RL 2.4.0
> Material 3.3.5
> 

It seems that the title formats are working. BTW _LMS_ does not automatically refresh the **_left pane_** browse page in (Dark) _Default Skin_. You'll have to do it yourself to check if the title format displays the correct ratings.
_Example:_ Set a new rating of 2 stars for some _artist name > album title > track title_. Then if you click on the _album title_, it should display the title format with the correct rating for the track. I've also checked Material 3.3.5. Works.

**Comment by cirdanlunae** [comment] 2023-07-25 19:14
Sorry for lack of response, was on vacation.

I'm still on 8.3.1 with piCorePlayer. Guessing v 8.4.0 hasn't reached PCP yet. I'll hold out until then, and when it gets updated I guess it'll work for me. Appreciate you coming back with the info!

**Comment by AF-1** [comment] 2023-07-28 09:40
8.3.1 is the _release_ branch of LMS and not updated very often. 8.4.0 is the _development_ branch. 
I'd use the **_stable bug fix_** branch (= release + bug fixes) which is at 8.3.**2** right now.

I've been keeping an eye on your issue and I still can't reproduce it with RL 2.4.2 + LMS 8.4.0 - 1688469516 @ Tue Jul 4.
So I'm closing this for now.

**Closed as completed by AF-1** 2023-07-28 09:40 UTC
Labels: unable to replicate
