### ISSUE TITLE
[ISSUE] Ratings of duplicate albums fails

### ISSUE THREAD

**Issue by grasshide** [AF-1/lms-ratingslight#7] opened 2024-12-10 13:01 UTC
## DESCRIBE THE BUG
When I upgrade music from mp3 to flac i have the same album twice in my collection. 
The rating for the "old" mp3 album is displayed as expected in the classic and in the material skin.
The "new" flac album (automatically/without creating any additional ratings) shows the ratings of the old mp3 album in the classic skin but the material skin does not show any ratings for the new album.
If the rating of a track of the new album gets changed (in the classic or the material skin), the change is also only visible in the classic skin (for both albums new and old) but nothing happens in the material skin.
A rescan of the library with the option of deleting the database first makes no difference to what I described.

I might have to mention that I previously used TrackStat. I installed it when I moved to Ratings Light.

## TO REPRODUCE
Steps to reproduce the behaviour:
1. duplicate an album
2. after a library rescan both albums show the same ratings in the classic skin
3. the material skin only shows the ratings for the original album
4. change a rating in the duplicate
5. the rating for the original AND the duplicate changes in the classic skin
6. the material skin only shows a changed rating for the original and no rating for the duplicate

<br><br>
## EXPECTED BEHAVIOR
ratings should be applied correctly
(not sure how lms/ratins-light behaves in case of album/song duplicates, especially after a library rescan)

<br><br>
## LOG EXCERPT
2[24-12-10 13:36:21.6081] Plugins::RatingsLight::Plugin::objectInfoHandler (871) objectType = trackArtist ## url = "file:///location_of_duplicate/Justin%20Timberlake/2013%20-%20The%2020+20%20Experience/09%20-%20Mirrors.flac"
[24-12-10 13:36:21.6101] Plugins::RatingsLight::Plugin::getRatedTracks (1004) objectType = artist ## countOnly = 1 ## trackID = 2219048 ## thisID = 426200
[24-12-10 13:36:21.6799] Plugins::RatingsLight::Plugin::getRatedTracks (1064) Pre-check found 66 rated tracks for artist with ID: 426200
[24-12-10 13:36:21.6800] Plugins::RatingsLight::Plugin::VFD_ratedtracks (1348) objectType = artist ## thisID = 426200 ## trackID = 2219048
[24-12-10 13:36:21.6801] Plugins::RatingsLight::Plugin::getRatedTracks (1004) objectType = artist ## countOnly = 0 ## trackID = 2219048 ## thisID = 426200
[24-12-10 13:36:21.7715] Plugins::RatingsLight::Plugin::getRatedTracks (1067) Fetched 66 rated tracks for artist with ID: 426200
[24-12-10 13:36:21.8183] Plugins::RatingsLight::Plugin::objectInfoHandler (871) objectType = trackAlbum ## url = "file:///location_of_duplicate/Justin%20Timberlake/2013%20-%20The%2020+20%20Experience/09%20-%20Mirrors.flac"
[24-12-10 13:36:21.8193] Plugins::RatingsLight::Plugin::getRatedTracks (1004) objectType = album ## countOnly = 1 ## trackID = 2219048 ## thisID = 136433
[24-12-10 13:36:21.8197] Plugins::RatingsLight::Plugin::getRatedTracks (1064) Pre-check found 0 rated tracks for album with ID: 136433
[24-12-10 13:36:21.8889] Plugins::RatingsLight::Plugin::objectInfoHandler (871) objectType = trackArtist ## url = "file:///location_of_duplicate/Justin%20Timberlake/2013%20-%20The%2020+20%20Experience/09%20-%20Mirrors.flac"
[24-12-10 13:36:21.8908] Plugins::RatingsLight::Plugin::getRatedTracks (1004) objectType = artist ## countOnly = 1 ## trackID = 2219048 ## thisID = 426200
[24-12-10 13:36:21.9348] Plugins::RatingsLight::Plugin::getRatedTracks (1064) Pre-check found 66 rated tracks for artist with ID: 426200
[24-12-10 13:36:21.9349] Plugins::RatingsLight::Plugin::VFD_ratedtracks (1348) objectType = artist ## thisID = 426200 ## trackID = 2219048
[24-12-10 13:36:21.9350] Plugins::RatingsLight::Plugin::getRatedTracks (1004) objectType = artist ## countOnly = 0 ## trackID = 2219048 ## thisID = 426200
[24-12-10 13:36:22.0241] Plugins::RatingsLight::Plugin::getRatedTracks (1067) Fetched 66 rated tracks for artist with ID: 426200
[24-12-10 13:36:22.0676] Plugins::RatingsLight::Plugin::objectInfoHandler (871) objectType = trackAlbum ## url = "file:///location_of_duplicate/Justin%20Timberlake/2013%20-%20The%2020+20%20Experience/09%20-%20Mirrors.flac"
[24-12-10 13:36:22.0687] Plugins::RatingsLight::Plugin::getRatedTracks (1004) objectType = album ## countOnly = 1 ## trackID = 2219048 ## thisID = 136433
[24-12-10 13:36:22.0690] Plugins::RatingsLight::Plugin::getRatedTracks (1064) Pre-check found 0 rated tracks for album with ID: 136433
[24-12-10 13:36:26.4609] Plugins::RatingsLight::Plugin::objectInfoHandler (871) objectType = trackArtist ## url = "file:///location_of_duplicate/Justin%20Timberlake/2013%20-%20The%2020+20%20Experience/09%20-%20Mirrors.flac"
[24-12-10 13:36:26.4632] Plugins::RatingsLight::Plugin::getRatedTracks (1004) objectType = artist ## countOnly = 1 ## trackID = 2219048 ## thisID = 426200
[24-12-10 13:36:26.5022] Plugins::RatingsLight::Plugin::getRatedTracks (1064) Pre-check found 66 rated tracks for artist with ID: 426200
[24-12-10 13:36:26.5023] Plugins::RatingsLight::Plugin::VFD_ratedtracks (1348) objectType = artist ## thisID = 426200 ## trackID = 2219048
[24-12-10 13:36:26.5024] Plugins::RatingsLight::Plugin::getRatedTracks (1004) objectType = artist ## countOnly = 0 ## trackID = 2219048 ## thisID = 426200
[24-12-10 13:36:26.5952] Plugins::RatingsLight::Plugin::getRatedTracks (1067) Fetched 66 rated tracks for artist with ID: 426200
[24-12-10 13:36:26.6382] Plugins::RatingsLight::Plugin::objectInfoHandler (871) objectType = trackAlbum ## url = "file:///location_of_duplicate/Justin%20Timberlake/2013%20-%20The%2020+20%20Experience/09%20-%20Mirrors.flac"
[24-12-10 13:36:26.6392] Plugins::RatingsLight::Plugin::getRatedTracks (1004) objectType = album ## countOnly = 1 ## trackID = 2219048 ## thisID = 136433
[24-12-10 13:36:26.6396] Plugins::RatingsLight::Plugin::getRatedTracks (1064) Pre-check found 0 rated tracks for album with ID: 136433
[24-12-10 13:36:26.6785] Plugins::RatingsLight::Plugin::objectInfoHandler (871) objectType = trackArtist ## url = "file:///location_of_duplicate/Justin%20Timberlake/2013%20-%20The%2020+20%20Experience/09%20-%20Mirrors.flac"
[24-12-10 13:36:26.6802] Plugins::RatingsLight::Plugin::getRatedTracks (1004) objectType = artist ## countOnly = 1 ## trackID = 2219048 ## thisID = 426200
[24-12-10 13:36:26.7174] Plugins::RatingsLight::Plugin::getRatedTracks (1064) Pre-check found 66 rated tracks for artist with ID: 426200
[24-12-10 13:36:26.7175] Plugins::RatingsLight::Plugin::VFD_ratedtracks (1348) objectType = artist ## thisID = 426200 ## trackID = 2219048
[24-12-10 13:36:26.7176] Plugins::RatingsLight::Plugin::getRatedTracks (1004) objectType = artist ## countOnly = 0 ## trackID = 2219048 ## thisID = 426200
[24-12-10 13:36:26.8046] Plugins::RatingsLight::Plugin::getRatedTracks (1067) Fetched 66 rated tracks for artist with ID: 426200
[24-12-10 13:36:26.8478] Plugins::RatingsLight::Plugin::objectInfoHandler (871) objectType = trackAlbum ## url = "file:///location_of_duplicate/Justin%20Timberlake/2013%20-%20The%2020+20%20Experience/09%20-%20Mirrors.flac"
[24-12-10 13:36:26.8488] Plugins::RatingsLight::Plugin::getRatedTracks (1004) objectType = album ## countOnly = 1 ## trackID = 2219048 ## thisID = 136433
[24-12-10 13:36:26.8492] Plugins::RatingsLight::Plugin::getRatedTracks (1064) Pre-check found 0 rated tracks for album with ID: 136433
[24-12-10 13:36:38.1540] Plugins::RatingsLight::Plugin::setRating (322) request params = { _incremental => undef, _rating => "3.5", _trackid => 2_219_048 }
[24-12-10 13:36:38.1547] Plugins::RatingsLight::Plugin::ratingValidator (2926) rating = 3.5 -- ratingScale = undef
[24-12-10 13:36:38.1583] Plugins::RatingsLight::Plugin::writeRatingToDB (2753) trackID = 2_219_048
trackURL = undef
trackURLmd5 = undef
track obj = 1
rating = 70
dontlogthis = undef
[24-12-10 13:36:38.1743] Plugins::RatingsLight::Plugin::writeRatingToDB (2780) Rating successful. Track title: Mirrors ## New rating = 3.5 (70)
[24-12-10 13:36:38.2139] Plugins::RatingsLight::Plugin::addToRecentlyRatedPlaylist (2664) Current playlist track count = 30. Max. allowed playlist track count = 30. Will remove 1 track(s) from the start of the playlist *before* adding new recently rated track.
[24-12-10 13:36:38.2539] Plugins::RatingsLight::Plugin::addToRecentlyRatedPlaylist (2672) Added track "Mirrors" to "Recently Rated Tracks" playlist

<br><br>
## VERSION INFO
Lyrion Music Server Version: 9.0.1 - 1733504989 @ Sat Dec 7 03:00:05 UTC 2024
Hostname: lms
Operating system: Debian (Docker) - EN - utf8
Platform Architecture: x86_64-linux
Database Version: SQLite

If the problem occurs with a specific web skin/controller (e.g. Material), please check whether it also occurs when using other web skins/controllers (e.g. LMS default skin).
Done.

**Comment by AF-1** [comment] 2024-12-11 14:37
I can't reproduce this. I assume that you don't use RL and TrackStat at the same time and that you meant that you **un**installed TS. Because running RL and TS at the same time or reinstalling TS could have similar effects to what you're describing.

In general, there are only 2 places where RL has part in **_displaying_** ratings: the track context / song info menu and RL title formats. 
Plugins / skins like Material ask LMS **directly** for the rating value. RL is not involved unless it's the track context / song info menu or a RL title format. So, Material track/album lists or play queue -> RL is not involved.

Have you checked the tags of your audio files? If they have MusicBrainz (track) IDs or RATING tracks, it might have sth to do with the behaviour you're describing.
Also, do **not** reinstall TrackStat (unless you've created a backup with RL before). TS might reset all ratings that you've set with RL in the meantime.

**Comment by grasshide** [comment] 2024-12-11 15:50
I (did not and) do not plan to reinstall TrackStat.

Most of my files are tagged with Picard and contain MusicBrainz tags. What is the expected behaviour in this case?
What is the best way to remove the "old" mp3s to contain/transfer my ratings?

Any mysql query that I can run that shines a light on this mystery?

**Comment by AF-1** [comment] 2024-12-11 18:42
If 2 tracks have identical MusicBrainz (track?) ID tags, IIRC LMS may **show** them as having the same track rating even if only one of them is rated. It may depend on which track LMS uses for matching (the one with the rating or not). Well, something along these lines anyway. The rating values in the LMS database should be ok though. And RL sets ratings using track ids, not MB IDs. 
So if you rate the new FLAC tracks with RL, the rating value in the LMS database for these tracks should be correct.

My suggestion: create a backup of your ratings with RL, rate your flac tracks, then move the duplicate mp3 tracks out of your LMS music folders, do a wipe rescan and after a while restart the server. LMS should now show the correct ratings for flac tracks. Although... the LMS persistent database with the rating values sometimes contains entries for dead tracks that are no longer part of the LMS library. I don't know how LMS would display ratings if this was the case for your old duplicate mp3s because it matches on MB IDs first and not on (invalid) track urls. In this case see if removing dead tracks helps (see below).

Here's some sqlite to get track titles and artist for tracks with duplicate MB ids:
````
select title,primary_artist from (select tracks.title as title, contributors.name as primary_artist from tracks join contributors on tracks.primary_artist = contributors.id where tracks.musicbrainz_id is not null group by tracks.musicbrainz_id having count(tracks.musicbrainz_id) > 1)
````

And should you need to remove dead tracks from the LMS tracks_persistent table (backup **everything** before though). 
Check if there are dead tracks:
````
select count(*) from tracks_persistent where urlmd5 not in (select urlmd5 from tracks where tracks.urlmd5 = tracks_persistent.urlmd5)
````

To remove dead tracks: **stop** LMS. Then do:
````
delete from tracks_persistent where urlmd5 not in (select urlmd5 from tracks where tracks.urlmd5 = tracks_persistent.urlmd5)
````

But don't blame me if this messes up your library/database. I'm assuming that you know what you're doing.

**Comment by grasshide** [comment] 2024-12-13 10:25
I had some time to anylyze the issue a bit. I no expert, but you should be able to reproduce this by adding a MB id to a track in the tracks_persistent db and duplicate that. Here an actual example of my db:

``` sql
.schema tracks_persistent
CREATE TABLE persist.tracks_persistent (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  url text NOT NULL,
  musicbrainz_id varchar(40),   -- musicbrainz uuid (36 bytes of text)
  added int(10),
  rating tinyint(1),
  playCount int(10),
  lastPlayed int(10)
, urlmd5 char(32) NOT NULL default '0');
```

``` sql
select * from tracks_persistent where tracks_persistent.url like "%20Pusher%20Love%20Girl%";
34476|file:///old_files/Justin%20Timberlake%20-%202013%20-%20The%202020%20Experience/01.%20Pusher%20Love%20Girl.flac|f10ce3b4-d079-471a-9d0d-0cd0a1ff018b|1641142715|50|33|1734082597|9b620e5e479eb800ed7d03fe6a223e19
59119|file:///new_files/Justin%20Timberlake/2013%20-%20The%2020+20%20Experience/01%20-%20Pusher%20Love%20Girl.flac|f10ce3b4-d079-471a-9d0d-0cd0a1ff018b|1733663960||||9c32e7a98011a712bc856b1a82f43d1b
```

I deleted the old files from the disk and did a full library delete and rebuild and a restart.

There are two issues in my opinion.
1.) RL does not store the rating (also not the playCount or lastPlayed) with the (correct) track in the tracks_persistent database (instead it somehow uses the MB id). Even if the track no longer exists.
2.) The material skin does rely on the rating of the track (and not the MB id). There also seems to be a bug (maybe in RL?) since there is no rating shown for the "new" track in material skin (maybe correct if it doesn't rely on the MB id) but no rating can be applied at all (with or without the "old" files present). The classic skin shows and applied the rating, but to the "dead" track.


I have quite a lot of dead tracks in my db and I'm afraid that this problem has been there for a while. If I just purge the dead tracks I probably loose a lot of ratings that have been written to MB ids instead of the correct tracks.
``` sql
select count(*) from tracks_persistent 
    where urlmd5 not in (select urlmd5 from tracks where tracks.urlmd5 = tracks_persistent.urlmd5);
4448
```

I'm quite bad with SQL. Is there a way to copy the values from the song with all the information (rating, playCount, lastPlayed) to all the other songs with the same MB id where this fields are null? Then deleting the dead track would be no problem.

Thank you for your help btw!

**Comment by AF-1** [comment] 2024-12-13 16:52
RL does not deal with play counts or date last played. They are directly handled by LMS. 
**LMS core** offers a rating method for the track object to get and set rating values which matches on MB ids and works for 99,9% of LMS users. 
Maybe I'll add an option in one of the next releases that allows users with corner use cases like yours to switch from the LMS method to an alternative RL method that makes sure only the unique track id is used to get/set track ratings. But that mean duplicating a part of the LMS core functionality which I don't really like. We'll see.

As for transferring rating values for your 4k dead tracks to their upgraded flac versions, there's no easy way. And unfortunately, I don't have the time to solve this. Here's an idea though, without any guarantees (dry run first):
- make 2 copies of persist.db
- rename one, in this example I added __source_ to the name
- in _persists_souce.db_: rename _tracks_persistent_ to `tracks_persistent_source`
- then attach persist.db (the other copy)
- then try:
````
update tracks_persistent set rating = (select rating from tracks_persistent_source where tracks_persistent.musicbrainz_id = tracks_persistent_source.musicbrainz_id and ifnull(rating,0) > 0)
````
I haven't tested this. That's what's your dry run is for.

**Comment by grasshide** [comment] 2024-12-13 18:55
I still think something is weird. Maybe this is a LMS bug that it rates dead tracks. Maybe it should just update all tracks with the same MB id instead of the first it finds.

Anyway, since this might really be a corner case I don't think it is worth coding a corner case for it.
Thank you for helping me understanding how things work.

I came up with this python script in the meantime to help me deal with this. Hopefully it helps someone else some day...

``` python
import sqlite3
from pathlib import Path

# library location
persist = 'persist.db'
library = 'library.db'
if not Path(persist).is_file() and not Path(library).is_file(): 
    persist = './conf/prefs/persist.db'
    library = './conf/cache/library.db'

# sqlite connection
con = sqlite3.connect(library)
cur = con.cursor()
cur.execute('ATTACH DATABASE ? AS persist', (persist,))

# select all tracks with duplicate musicbrainz_ids in the tracks_persistent db
mb_duplicates = '''
    SELECT a.*
    FROM tracks_persistent a
    JOIN (SELECT musicbrainz_id, COUNT(*)
    FROM tracks_persistent
    GROUP BY musicbrainz_id
    HAVING count(*) > 1 ) b
    ON a.musicbrainz_id = b.musicbrainz_id
    ORDER BY a.musicbrainz_id;
'''

upd_query = '''
UPDATE tracks_persistent
SET rating = ?,
    playCount = ?,
    lastPlayed = ?,
    added = ?
WHERE id=?;
'''

del_dead = '''
delete from tracks_persistent 
where urlmd5 not in (select urlmd5 from tracks where tracks.urlmd5 = tracks_persistent.urlmd5) 
and tracks_persistent.id = ?;
'''

def query_sql(query):

    # execute query
    cur.execute(query)

    # fetch column names and put result in a dict
    columns = cur.description 
    result = [{columns[index][0]:column for index, column in enumerate(value)} for value in cur.fetchall()]

    return result


def update_query(ids, lastPlayed, playCount, rating, added):

    for id in ids:
        # execute query
        print("updating id: " + str(id) + " with rating: " + str(rating))
        cur.execute(upd_query, (rating, playCount, lastPlayed, added, id,))


# use musicbrainz_id as additional index
songDict = {}
for dct in query_sql(mb_duplicates):
    songDict.setdefault(dct['musicbrainz_id'], []).append(dct)


# process songs
for song_group in songDict:

    lastPlayed = None
    playCount = None
    rating = None
    added = None
    ids = []
    update = False

    for song in songDict[song_group]:
        
        if song["rating"] is None: # songs to update later
            ids.append(song["id"])
        if song["rating"] is not None:
            update = True # make sure at lease one song has a rating
            rating = song["rating"]
            lastPlayed = song["lastPlayed"]
            playCount = song["playCount"]
            added = song["added"]

    # execute update
    if update:
        update_query(ids, lastPlayed, playCount, rating, added)


# delete dead tracks
for song_group in songDict:
    for song in songDict[song_group]:
        cur.execute(del_dead, (song["id"],))

# close the connection
con.commit()  
con.close()
```

**Closed as completed** 2024-12-13 18:56 UTC
Labels: bug: not a bug
